"""Change status to Enum in PartFlight

Revision ID: 66f533be3591
Revises: c67320e2f236
Create Date: 2025-03-15 22:55:28.112648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66f533be3591'
down_revision: Union[str, None] = 'c67320e2f236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('part_flight', 'status',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('CANCELLED', 'ONTIME', 'DELAYED', name='statusflightenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('part_flight', 'status',
               existing_type=sa.Enum('CANCELLED', 'ONTIME', 'DELAYED', name='statusflightenum'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
