"""Change partflight

Revision ID: 8968628f8285
Revises: 3e48fa70c029
Create Date: 2025-04-05 22:13:14.203124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8968628f8285'
down_revision: Union[str, None] = '3e48fa70c029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('part_flight', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_flight', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
