"""Change nullable for model Guest

Revision ID: 9b9b638fa253
Revises: 23f6797ac2c7
Create Date: 2025-04-06 23:12:41.007509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b9b638fa253'
down_revision: Union[str, None] = '23f6797ac2c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('guest', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('guest', 'date_of_birth',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('guest', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('guest', 'phone',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest', 'phone',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('guest', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('guest', 'date_of_birth',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('guest', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('guest', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
