"""change value of enum

Revision ID: a30ae9aaec91
Revises: 66f533be3591
Create Date: 2025-03-15 23:18:48.910474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a30ae9aaec91'
down_revision: Union[str, None] = '66f533be3591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('CUSTOMER', 'STAFF', 'STAFFFLIGHTSCHEUDLE', 'ADMIN'),
               type_=sa.Enum('CUSTOMER', 'STAFF', 'STAFF_FLIGHT_SCHEDULE', 'ADMIN', name='userenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.Enum('CUSTOMER', 'STAFF', 'STAFF_FLIGHT_SCHEDULE', 'ADMIN', name='userenum'),
               type_=mysql.ENUM('CUSTOMER', 'STAFF', 'STAFFFLIGHTSCHEUDLE', 'ADMIN'),
               existing_nullable=True)
    # ### end Alembic commands ###
