"""Add model systemrule

Revision ID: b295bbc6d8f8
Revises: 9b9b638fa253
Create Date: 2025-04-07 15:50:52.705845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b295bbc6d8f8'
down_revision: Union[str, None] = '9b9b638fa253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_rule',
    sa.Column('max_layover_airports', sa.Integer(), nullable=True),
    sa.Column('min_flight_duration', sa.Integer(), nullable=True),
    sa.Column('min_layover_duration', sa.Integer(), nullable=True),
    sa.Column('max_layover_duration', sa.Integer(), nullable=True),
    sa.Column('max_ticket_classes', sa.Integer(), nullable=True),
    sa.Column('latest_booking_hour', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_rule')
    # ### end Alembic commands ###
