"""Add status enum for class Seats

Revision ID: b974f46beefb
Revises: af9c52f816e1
Create Date: 2025-03-31 09:48:17.922476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b974f46beefb'
down_revision: Union[str, None] = 'af9c52f816e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat', sa.Column('status', sa.Enum('AVAILABLE', 'BOOKED', name='statusseat'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat', 'status')
    # ### end Alembic commands ###
