"""Add methodEnum

Revision ID: c8697dd23fd2
Revises: b974f46beefb
Create Date: 2025-04-02 16:41:06.847991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c8697dd23fd2'
down_revision: Union[str, None] = 'b974f46beefb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'payment_method',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('CASH', 'CARD', name='methodenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'payment_method',
               existing_type=sa.Enum('CASH', 'CARD', name='methodenum'),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
