"""Change some things in models.py

Revision ID: e82755dab585
Revises: 4e6486550f59
Create Date: 2025-04-03 20:54:15.904835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e82755dab585'
down_revision: Union[str, None] = '4e6486550f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flight_ibfk_1', 'flight', type_='foreignkey')
    op.create_foreign_key(None, 'flight', 'plane', ['plane_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('part_flight_ibfk_2', 'part_flight', type_='foreignkey')
    op.create_foreign_key(None, 'part_flight', 'flight', ['flight_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('plane_ibfk_1', 'plane', type_='foreignkey')
    op.create_foreign_key(None, 'plane', 'airline', ['airline_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('route_ibfk_1', 'route', type_='foreignkey')
    op.drop_constraint('route_ibfk_2', 'route', type_='foreignkey')
    op.create_foreign_key(None, 'route', 'airport', ['end_airport'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'route', 'airport', ['start_airport'], ['id'], ondelete='CASCADE')
    op.drop_constraint('seat_ibfk_1', 'seat', type_='foreignkey')
    op.create_foreign_key(None, 'seat', 'plane', ['plane_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ticket_ibfk_2', 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ticket_ibfk_2', 'ticket', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'seat', type_='foreignkey')
    op.create_foreign_key('seat_ibfk_1', 'seat', 'plane', ['plane_id'], ['id'])
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.create_foreign_key('route_ibfk_2', 'route', 'airport', ['end_airport'], ['id'])
    op.create_foreign_key('route_ibfk_1', 'route', 'airport', ['start_airport'], ['id'])
    op.drop_constraint(None, 'plane', type_='foreignkey')
    op.create_foreign_key('plane_ibfk_1', 'plane', 'airline', ['airline_id'], ['id'])
    op.drop_constraint(None, 'part_flight', type_='foreignkey')
    op.create_foreign_key('part_flight_ibfk_2', 'part_flight', 'flight', ['flight_id'], ['id'])
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.create_foreign_key('flight_ibfk_1', 'flight', 'plane', ['plane_id'], ['id'])
    # ### end Alembic commands ###
